/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as SolicitacoesRouteImport } from './routes/solicitacoes'
import { Route as OcorrenciasRouteImport } from './routes/ocorrencias'
import { Route as MudancasRouteImport } from './routes/mudancas'
import { Route as MoradoresRouteImport } from './routes/moradores'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LiberacoesRouteImport } from './routes/liberacoes'
import { Route as FornecedoresRouteImport } from './routes/fornecedores'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as CondominiosRouteImport } from './routes/condominios'
import { Route as ChamadosRouteImport } from './routes/chamados'
import { Route as AvisosRouteImport } from './routes/avisos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RelatoriosIndexRouteImport } from './routes/relatorios.index'
import { Route as CondominiosIndexRouteImport } from './routes/condominios.index'
import { Route as RelatoriosOcorrenciasRouteImport } from './routes/relatorios.ocorrencias'
import { Route as OcorrenciasNovoRouteImport } from './routes/ocorrencias.novo'
import { Route as MudancasNovoRouteImport } from './routes/mudancas.novo'
import { Route as EventosNovoRouteImport } from './routes/eventos.novo'
import { Route as CondominiosNovoRouteImport } from './routes/condominios.novo'
import { Route as CondominiosIdRouteImport } from './routes/condominios.$id'
import { Route as ChamadosNovoRouteImport } from './routes/chamados.novo'
import { Route as AvisosNovoRouteImport } from './routes/avisos.novo'
import { Route as CondominiosIdIndexRouteImport } from './routes/condominios.$id.index'
import { Route as CondominiosIdEditarRouteImport } from './routes/condominios.$id.editar'

const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const SolicitacoesRoute = SolicitacoesRouteImport.update({
  id: '/solicitacoes',
  path: '/solicitacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const OcorrenciasRoute = OcorrenciasRouteImport.update({
  id: '/ocorrencias',
  path: '/ocorrencias',
  getParentRoute: () => rootRouteImport,
} as any)
const MudancasRoute = MudancasRouteImport.update({
  id: '/mudancas',
  path: '/mudancas',
  getParentRoute: () => rootRouteImport,
} as any)
const MoradoresRoute = MoradoresRouteImport.update({
  id: '/moradores',
  path: '/moradores',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LiberacoesRoute = LiberacoesRouteImport.update({
  id: '/liberacoes',
  path: '/liberacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const FornecedoresRoute = FornecedoresRouteImport.update({
  id: '/fornecedores',
  path: '/fornecedores',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const CondominiosRoute = CondominiosRouteImport.update({
  id: '/condominios',
  path: '/condominios',
  getParentRoute: () => rootRouteImport,
} as any)
const ChamadosRoute = ChamadosRouteImport.update({
  id: '/chamados',
  path: '/chamados',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisosRoute = AvisosRouteImport.update({
  id: '/avisos',
  path: '/avisos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosIndexRoute = RelatoriosIndexRouteImport.update({
  id: '/relatorios/',
  path: '/relatorios/',
  getParentRoute: () => rootRouteImport,
} as any)
const CondominiosIndexRoute = CondominiosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CondominiosRoute,
} as any)
const RelatoriosOcorrenciasRoute = RelatoriosOcorrenciasRouteImport.update({
  id: '/relatorios/ocorrencias',
  path: '/relatorios/ocorrencias',
  getParentRoute: () => rootRouteImport,
} as any)
const OcorrenciasNovoRoute = OcorrenciasNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => OcorrenciasRoute,
} as any)
const MudancasNovoRoute = MudancasNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => MudancasRoute,
} as any)
const EventosNovoRoute = EventosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => EventosRoute,
} as any)
const CondominiosNovoRoute = CondominiosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => CondominiosRoute,
} as any)
const CondominiosIdRoute = CondominiosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CondominiosRoute,
} as any)
const ChamadosNovoRoute = ChamadosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => ChamadosRoute,
} as any)
const AvisosNovoRoute = AvisosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AvisosRoute,
} as any)
const CondominiosIdIndexRoute = CondominiosIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CondominiosIdRoute,
} as any)
const CondominiosIdEditarRoute = CondominiosIdEditarRouteImport.update({
  id: '/editar',
  path: '/editar',
  getParentRoute: () => CondominiosIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/avisos': typeof AvisosRouteWithChildren
  '/chamados': typeof ChamadosRouteWithChildren
  '/condominios': typeof CondominiosRouteWithChildren
  '/eventos': typeof EventosRouteWithChildren
  '/fornecedores': typeof FornecedoresRoute
  '/liberacoes': typeof LiberacoesRoute
  '/login': typeof LoginRoute
  '/moradores': typeof MoradoresRoute
  '/mudancas': typeof MudancasRouteWithChildren
  '/ocorrencias': typeof OcorrenciasRouteWithChildren
  '/solicitacoes': typeof SolicitacoesRoute
  '/usuarios': typeof UsuariosRoute
  '/avisos/novo': typeof AvisosNovoRoute
  '/chamados/novo': typeof ChamadosNovoRoute
  '/condominios/$id': typeof CondominiosIdRouteWithChildren
  '/condominios/novo': typeof CondominiosNovoRoute
  '/eventos/novo': typeof EventosNovoRoute
  '/mudancas/novo': typeof MudancasNovoRoute
  '/ocorrencias/novo': typeof OcorrenciasNovoRoute
  '/relatorios/ocorrencias': typeof RelatoriosOcorrenciasRoute
  '/condominios/': typeof CondominiosIndexRoute
  '/relatorios/': typeof RelatoriosIndexRoute
  '/condominios/$id/editar': typeof CondominiosIdEditarRoute
  '/condominios/$id/': typeof CondominiosIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/avisos': typeof AvisosRouteWithChildren
  '/chamados': typeof ChamadosRouteWithChildren
  '/eventos': typeof EventosRouteWithChildren
  '/fornecedores': typeof FornecedoresRoute
  '/liberacoes': typeof LiberacoesRoute
  '/login': typeof LoginRoute
  '/moradores': typeof MoradoresRoute
  '/mudancas': typeof MudancasRouteWithChildren
  '/ocorrencias': typeof OcorrenciasRouteWithChildren
  '/solicitacoes': typeof SolicitacoesRoute
  '/usuarios': typeof UsuariosRoute
  '/avisos/novo': typeof AvisosNovoRoute
  '/chamados/novo': typeof ChamadosNovoRoute
  '/condominios/novo': typeof CondominiosNovoRoute
  '/eventos/novo': typeof EventosNovoRoute
  '/mudancas/novo': typeof MudancasNovoRoute
  '/ocorrencias/novo': typeof OcorrenciasNovoRoute
  '/relatorios/ocorrencias': typeof RelatoriosOcorrenciasRoute
  '/condominios': typeof CondominiosIndexRoute
  '/relatorios': typeof RelatoriosIndexRoute
  '/condominios/$id/editar': typeof CondominiosIdEditarRoute
  '/condominios/$id': typeof CondominiosIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/avisos': typeof AvisosRouteWithChildren
  '/chamados': typeof ChamadosRouteWithChildren
  '/condominios': typeof CondominiosRouteWithChildren
  '/eventos': typeof EventosRouteWithChildren
  '/fornecedores': typeof FornecedoresRoute
  '/liberacoes': typeof LiberacoesRoute
  '/login': typeof LoginRoute
  '/moradores': typeof MoradoresRoute
  '/mudancas': typeof MudancasRouteWithChildren
  '/ocorrencias': typeof OcorrenciasRouteWithChildren
  '/solicitacoes': typeof SolicitacoesRoute
  '/usuarios': typeof UsuariosRoute
  '/avisos/novo': typeof AvisosNovoRoute
  '/chamados/novo': typeof ChamadosNovoRoute
  '/condominios/$id': typeof CondominiosIdRouteWithChildren
  '/condominios/novo': typeof CondominiosNovoRoute
  '/eventos/novo': typeof EventosNovoRoute
  '/mudancas/novo': typeof MudancasNovoRoute
  '/ocorrencias/novo': typeof OcorrenciasNovoRoute
  '/relatorios/ocorrencias': typeof RelatoriosOcorrenciasRoute
  '/condominios/': typeof CondominiosIndexRoute
  '/relatorios/': typeof RelatoriosIndexRoute
  '/condominios/$id/editar': typeof CondominiosIdEditarRoute
  '/condominios/$id/': typeof CondominiosIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/avisos'
    | '/chamados'
    | '/condominios'
    | '/eventos'
    | '/fornecedores'
    | '/liberacoes'
    | '/login'
    | '/moradores'
    | '/mudancas'
    | '/ocorrencias'
    | '/solicitacoes'
    | '/usuarios'
    | '/avisos/novo'
    | '/chamados/novo'
    | '/condominios/$id'
    | '/condominios/novo'
    | '/eventos/novo'
    | '/mudancas/novo'
    | '/ocorrencias/novo'
    | '/relatorios/ocorrencias'
    | '/condominios/'
    | '/relatorios/'
    | '/condominios/$id/editar'
    | '/condominios/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/avisos'
    | '/chamados'
    | '/eventos'
    | '/fornecedores'
    | '/liberacoes'
    | '/login'
    | '/moradores'
    | '/mudancas'
    | '/ocorrencias'
    | '/solicitacoes'
    | '/usuarios'
    | '/avisos/novo'
    | '/chamados/novo'
    | '/condominios/novo'
    | '/eventos/novo'
    | '/mudancas/novo'
    | '/ocorrencias/novo'
    | '/relatorios/ocorrencias'
    | '/condominios'
    | '/relatorios'
    | '/condominios/$id/editar'
    | '/condominios/$id'
  id:
    | '__root__'
    | '/'
    | '/avisos'
    | '/chamados'
    | '/condominios'
    | '/eventos'
    | '/fornecedores'
    | '/liberacoes'
    | '/login'
    | '/moradores'
    | '/mudancas'
    | '/ocorrencias'
    | '/solicitacoes'
    | '/usuarios'
    | '/avisos/novo'
    | '/chamados/novo'
    | '/condominios/$id'
    | '/condominios/novo'
    | '/eventos/novo'
    | '/mudancas/novo'
    | '/ocorrencias/novo'
    | '/relatorios/ocorrencias'
    | '/condominios/'
    | '/relatorios/'
    | '/condominios/$id/editar'
    | '/condominios/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvisosRoute: typeof AvisosRouteWithChildren
  ChamadosRoute: typeof ChamadosRouteWithChildren
  CondominiosRoute: typeof CondominiosRouteWithChildren
  EventosRoute: typeof EventosRouteWithChildren
  FornecedoresRoute: typeof FornecedoresRoute
  LiberacoesRoute: typeof LiberacoesRoute
  LoginRoute: typeof LoginRoute
  MoradoresRoute: typeof MoradoresRoute
  MudancasRoute: typeof MudancasRouteWithChildren
  OcorrenciasRoute: typeof OcorrenciasRouteWithChildren
  SolicitacoesRoute: typeof SolicitacoesRoute
  UsuariosRoute: typeof UsuariosRoute
  RelatoriosOcorrenciasRoute: typeof RelatoriosOcorrenciasRoute
  RelatoriosIndexRoute: typeof RelatoriosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solicitacoes': {
      id: '/solicitacoes'
      path: '/solicitacoes'
      fullPath: '/solicitacoes'
      preLoaderRoute: typeof SolicitacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ocorrencias': {
      id: '/ocorrencias'
      path: '/ocorrencias'
      fullPath: '/ocorrencias'
      preLoaderRoute: typeof OcorrenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mudancas': {
      id: '/mudancas'
      path: '/mudancas'
      fullPath: '/mudancas'
      preLoaderRoute: typeof MudancasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moradores': {
      id: '/moradores'
      path: '/moradores'
      fullPath: '/moradores'
      preLoaderRoute: typeof MoradoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/liberacoes': {
      id: '/liberacoes'
      path: '/liberacoes'
      fullPath: '/liberacoes'
      preLoaderRoute: typeof LiberacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fornecedores': {
      id: '/fornecedores'
      path: '/fornecedores'
      fullPath: '/fornecedores'
      preLoaderRoute: typeof FornecedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/condominios': {
      id: '/condominios'
      path: '/condominios'
      fullPath: '/condominios'
      preLoaderRoute: typeof CondominiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chamados': {
      id: '/chamados'
      path: '/chamados'
      fullPath: '/chamados'
      preLoaderRoute: typeof ChamadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avisos': {
      id: '/avisos'
      path: '/avisos'
      fullPath: '/avisos'
      preLoaderRoute: typeof AvisosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios/': {
      id: '/relatorios/'
      path: '/relatorios'
      fullPath: '/relatorios/'
      preLoaderRoute: typeof RelatoriosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/condominios/': {
      id: '/condominios/'
      path: '/'
      fullPath: '/condominios/'
      preLoaderRoute: typeof CondominiosIndexRouteImport
      parentRoute: typeof CondominiosRoute
    }
    '/relatorios/ocorrencias': {
      id: '/relatorios/ocorrencias'
      path: '/relatorios/ocorrencias'
      fullPath: '/relatorios/ocorrencias'
      preLoaderRoute: typeof RelatoriosOcorrenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ocorrencias/novo': {
      id: '/ocorrencias/novo'
      path: '/novo'
      fullPath: '/ocorrencias/novo'
      preLoaderRoute: typeof OcorrenciasNovoRouteImport
      parentRoute: typeof OcorrenciasRoute
    }
    '/mudancas/novo': {
      id: '/mudancas/novo'
      path: '/novo'
      fullPath: '/mudancas/novo'
      preLoaderRoute: typeof MudancasNovoRouteImport
      parentRoute: typeof MudancasRoute
    }
    '/eventos/novo': {
      id: '/eventos/novo'
      path: '/novo'
      fullPath: '/eventos/novo'
      preLoaderRoute: typeof EventosNovoRouteImport
      parentRoute: typeof EventosRoute
    }
    '/condominios/novo': {
      id: '/condominios/novo'
      path: '/novo'
      fullPath: '/condominios/novo'
      preLoaderRoute: typeof CondominiosNovoRouteImport
      parentRoute: typeof CondominiosRoute
    }
    '/condominios/$id': {
      id: '/condominios/$id'
      path: '/$id'
      fullPath: '/condominios/$id'
      preLoaderRoute: typeof CondominiosIdRouteImport
      parentRoute: typeof CondominiosRoute
    }
    '/chamados/novo': {
      id: '/chamados/novo'
      path: '/novo'
      fullPath: '/chamados/novo'
      preLoaderRoute: typeof ChamadosNovoRouteImport
      parentRoute: typeof ChamadosRoute
    }
    '/avisos/novo': {
      id: '/avisos/novo'
      path: '/novo'
      fullPath: '/avisos/novo'
      preLoaderRoute: typeof AvisosNovoRouteImport
      parentRoute: typeof AvisosRoute
    }
    '/condominios/$id/': {
      id: '/condominios/$id/'
      path: '/'
      fullPath: '/condominios/$id/'
      preLoaderRoute: typeof CondominiosIdIndexRouteImport
      parentRoute: typeof CondominiosIdRoute
    }
    '/condominios/$id/editar': {
      id: '/condominios/$id/editar'
      path: '/editar'
      fullPath: '/condominios/$id/editar'
      preLoaderRoute: typeof CondominiosIdEditarRouteImport
      parentRoute: typeof CondominiosIdRoute
    }
  }
}

interface AvisosRouteChildren {
  AvisosNovoRoute: typeof AvisosNovoRoute
}

const AvisosRouteChildren: AvisosRouteChildren = {
  AvisosNovoRoute: AvisosNovoRoute,
}

const AvisosRouteWithChildren =
  AvisosRoute._addFileChildren(AvisosRouteChildren)

interface ChamadosRouteChildren {
  ChamadosNovoRoute: typeof ChamadosNovoRoute
}

const ChamadosRouteChildren: ChamadosRouteChildren = {
  ChamadosNovoRoute: ChamadosNovoRoute,
}

const ChamadosRouteWithChildren = ChamadosRoute._addFileChildren(
  ChamadosRouteChildren,
)

interface CondominiosIdRouteChildren {
  CondominiosIdEditarRoute: typeof CondominiosIdEditarRoute
  CondominiosIdIndexRoute: typeof CondominiosIdIndexRoute
}

const CondominiosIdRouteChildren: CondominiosIdRouteChildren = {
  CondominiosIdEditarRoute: CondominiosIdEditarRoute,
  CondominiosIdIndexRoute: CondominiosIdIndexRoute,
}

const CondominiosIdRouteWithChildren = CondominiosIdRoute._addFileChildren(
  CondominiosIdRouteChildren,
)

interface CondominiosRouteChildren {
  CondominiosIdRoute: typeof CondominiosIdRouteWithChildren
  CondominiosNovoRoute: typeof CondominiosNovoRoute
  CondominiosIndexRoute: typeof CondominiosIndexRoute
}

const CondominiosRouteChildren: CondominiosRouteChildren = {
  CondominiosIdRoute: CondominiosIdRouteWithChildren,
  CondominiosNovoRoute: CondominiosNovoRoute,
  CondominiosIndexRoute: CondominiosIndexRoute,
}

const CondominiosRouteWithChildren = CondominiosRoute._addFileChildren(
  CondominiosRouteChildren,
)

interface EventosRouteChildren {
  EventosNovoRoute: typeof EventosNovoRoute
}

const EventosRouteChildren: EventosRouteChildren = {
  EventosNovoRoute: EventosNovoRoute,
}

const EventosRouteWithChildren =
  EventosRoute._addFileChildren(EventosRouteChildren)

interface MudancasRouteChildren {
  MudancasNovoRoute: typeof MudancasNovoRoute
}

const MudancasRouteChildren: MudancasRouteChildren = {
  MudancasNovoRoute: MudancasNovoRoute,
}

const MudancasRouteWithChildren = MudancasRoute._addFileChildren(
  MudancasRouteChildren,
)

interface OcorrenciasRouteChildren {
  OcorrenciasNovoRoute: typeof OcorrenciasNovoRoute
}

const OcorrenciasRouteChildren: OcorrenciasRouteChildren = {
  OcorrenciasNovoRoute: OcorrenciasNovoRoute,
}

const OcorrenciasRouteWithChildren = OcorrenciasRoute._addFileChildren(
  OcorrenciasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvisosRoute: AvisosRouteWithChildren,
  ChamadosRoute: ChamadosRouteWithChildren,
  CondominiosRoute: CondominiosRouteWithChildren,
  EventosRoute: EventosRouteWithChildren,
  FornecedoresRoute: FornecedoresRoute,
  LiberacoesRoute: LiberacoesRoute,
  LoginRoute: LoginRoute,
  MoradoresRoute: MoradoresRoute,
  MudancasRoute: MudancasRouteWithChildren,
  OcorrenciasRoute: OcorrenciasRouteWithChildren,
  SolicitacoesRoute: SolicitacoesRoute,
  UsuariosRoute: UsuariosRoute,
  RelatoriosOcorrenciasRoute: RelatoriosOcorrenciasRoute,
  RelatoriosIndexRoute: RelatoriosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
