/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as OcorrenciasRouteImport } from './routes/ocorrencias'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CondominiosRouteImport } from './routes/condominios'
import { Route as AvisosRouteImport } from './routes/avisos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CondominiosIndexRouteImport } from './routes/condominios.index'
import { Route as OcorrenciasNovoRouteImport } from './routes/ocorrencias.novo'

const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const OcorrenciasRoute = OcorrenciasRouteImport.update({
  id: '/ocorrencias',
  path: '/ocorrencias',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CondominiosRoute = CondominiosRouteImport.update({
  id: '/condominios',
  path: '/condominios',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisosRoute = AvisosRouteImport.update({
  id: '/avisos',
  path: '/avisos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CondominiosIndexRoute = CondominiosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CondominiosRoute,
} as any)
const OcorrenciasNovoRoute = OcorrenciasNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => OcorrenciasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/avisos': typeof AvisosRoute
  '/condominios': typeof CondominiosRouteWithChildren
  '/login': typeof LoginRoute
  '/ocorrencias': typeof OcorrenciasRouteWithChildren
  '/usuarios': typeof UsuariosRoute
  '/ocorrencias/novo': typeof OcorrenciasNovoRoute
  '/condominios/': typeof CondominiosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/avisos': typeof AvisosRoute
  '/login': typeof LoginRoute
  '/ocorrencias': typeof OcorrenciasRouteWithChildren
  '/usuarios': typeof UsuariosRoute
  '/ocorrencias/novo': typeof OcorrenciasNovoRoute
  '/condominios': typeof CondominiosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/avisos': typeof AvisosRoute
  '/condominios': typeof CondominiosRouteWithChildren
  '/login': typeof LoginRoute
  '/ocorrencias': typeof OcorrenciasRouteWithChildren
  '/usuarios': typeof UsuariosRoute
  '/ocorrencias/novo': typeof OcorrenciasNovoRoute
  '/condominios/': typeof CondominiosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/avisos'
    | '/condominios'
    | '/login'
    | '/ocorrencias'
    | '/usuarios'
    | '/ocorrencias/novo'
    | '/condominios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/avisos'
    | '/login'
    | '/ocorrencias'
    | '/usuarios'
    | '/ocorrencias/novo'
    | '/condominios'
  id:
    | '__root__'
    | '/'
    | '/avisos'
    | '/condominios'
    | '/login'
    | '/ocorrencias'
    | '/usuarios'
    | '/ocorrencias/novo'
    | '/condominios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvisosRoute: typeof AvisosRoute
  CondominiosRoute: typeof CondominiosRouteWithChildren
  LoginRoute: typeof LoginRoute
  OcorrenciasRoute: typeof OcorrenciasRouteWithChildren
  UsuariosRoute: typeof UsuariosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ocorrencias': {
      id: '/ocorrencias'
      path: '/ocorrencias'
      fullPath: '/ocorrencias'
      preLoaderRoute: typeof OcorrenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/condominios': {
      id: '/condominios'
      path: '/condominios'
      fullPath: '/condominios'
      preLoaderRoute: typeof CondominiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avisos': {
      id: '/avisos'
      path: '/avisos'
      fullPath: '/avisos'
      preLoaderRoute: typeof AvisosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/condominios/': {
      id: '/condominios/'
      path: '/'
      fullPath: '/condominios/'
      preLoaderRoute: typeof CondominiosIndexRouteImport
      parentRoute: typeof CondominiosRoute
    }
    '/ocorrencias/novo': {
      id: '/ocorrencias/novo'
      path: '/novo'
      fullPath: '/ocorrencias/novo'
      preLoaderRoute: typeof OcorrenciasNovoRouteImport
      parentRoute: typeof OcorrenciasRoute
    }
  }
}

interface CondominiosRouteChildren {
  CondominiosIndexRoute: typeof CondominiosIndexRoute
}

const CondominiosRouteChildren: CondominiosRouteChildren = {
  CondominiosIndexRoute: CondominiosIndexRoute,
}

const CondominiosRouteWithChildren = CondominiosRoute._addFileChildren(
  CondominiosRouteChildren,
)

interface OcorrenciasRouteChildren {
  OcorrenciasNovoRoute: typeof OcorrenciasNovoRoute
}

const OcorrenciasRouteChildren: OcorrenciasRouteChildren = {
  OcorrenciasNovoRoute: OcorrenciasNovoRoute,
}

const OcorrenciasRouteWithChildren = OcorrenciasRoute._addFileChildren(
  OcorrenciasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvisosRoute: AvisosRoute,
  CondominiosRoute: CondominiosRouteWithChildren,
  LoginRoute: LoginRoute,
  OcorrenciasRoute: OcorrenciasRouteWithChildren,
  UsuariosRoute: UsuariosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
